use bson::oid::ObjectId;
use chrono::Utc;
use serde::{Deserialize, Serialize};
use validator::Validate;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct UserProfile {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    pub username: String,
    pub email: String, // TODO: Add email validation
    #[serde(default)]
    pub allergies: Vec<String>,
    #[serde(default)]
    pub dietary_preferences: Vec<String>,
    #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl UserProfile {
    pub fn new(username: String, email: String) -> Self {
        let now = chrono::Utc::now();
        UserProfile {
            id: None,
            username,
            email,
            allergies: Vec::new(),
            dietary_preferences: Vec::new(),
            created_at: now,
            updated_at: now,
        }
    }

    pub fn from_payload(payload: CreateUserProfilePayload) -> Self {
        let now = Utc::now();
        UserProfile {
            id: None, // ID is generated by MongoDB
            username: payload.username,
            email: payload.email,
            allergies: payload.allergies.unwrap_or_default(),
            dietary_preferences: payload.dietary_preferences.unwrap_or_default(),
            created_at: now,
            updated_at: now,
        }
    }
}

/// Payload for creating a new user profile via the API.
#[derive(Deserialize, Validate, Debug)]
pub struct CreateUserProfilePayload {
    #[validate(length(min = 3, message = "Username must be at least 3 characters long"))]
    pub username: String,

    #[validate(email(message = "Invalid email format"))]
    pub email: String,

    #[serde(default)]
    pub allergies: Option<Vec<String>>,

    #[serde(default)]
    pub dietary_preferences: Option<Vec<String>>,
}
